### ISSUE TITLE
video layout

### ISSUE THREAD

**Issue by ghost** [mlyhoops/TorBots-Website#5]
From line 492, css class or positions(like absolute and fixed) can be changed to arrange the two videos responsively.  I will look into how it should be if you can not figure out. Thanks.

**Comment by mlyhoops** [comment]
I still used the bootstrap layout but I put them into one container so now it will respond to the size of the window better

**Comment by ghost** [comment]
It looks good. Do you want to try to add col-md-6 or/and col-lg-12 etc for various devices? Thanks.
